### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getUser')

### ISSUE THREAD

**Issue by rodbs** [mitchelvanbever/remix-auth-supabase#46]
### Describe the bug

```
TypeError: Cannot read properties of undefined (reading 'getUser')
    at SupabaseStrategy.getUser (C:\sources\igls-remix\node_modules\remix-auth-supabase\build\index.js:45:87)
    at SupabaseStrategy.checkSession (C:\sources\igls-remix\node_modules\remix-auth-supabase\build\index.js:72:33)
    at loader10 (C:\sources\igls-remix\app\routes\___auth\cuenta.tsx:11:19)
    at Object.callRouteLoaderRR (C:\sources\igls-remix\node_modules\@remix-run\server-runtime\dist\data.js:41:16)
    at callLoaderOrAction (C:\sources\igls-remix\node_modules\@remix-run\router\router.ts:2638:14)
    at async Promise.all (index 0)
    at loadRouteData (C:\sources\igls-remix\node_modules\@remix-run\router\router.ts:2306:19)
    at queryImpl (C:\sources\igls-remix\node_modules\@remix-run\router\router.ts:2110:20)
    at Object.queryRoute (C:\sources\igls-remix\node_modules\@remix-run\router\router.ts:2061:18)
    at handleDataRequestRR `(C:\sources\igls-remix\node_modules\@remix-run\server-runtime\dist\server.js:63:20)
```

### Your Example Website or App

not yet

### Steps to Reproduce the Bug or Issue

1. I'm using the oatuh example
2. After being redirect to the private page, I get this error
3. If  I go to the login page, I also get this error
4. To fix it I have to delete the cookie 'sb'

### Expected behavior

To logins smoothly

### Platform

- OS: Windows
- Browser: Chrome
- Version: 106

### Additional context

Sometimes the login gets stuck at the oauth/callback. I've changed the `useSubmit` for a `useFetcher` as described in other bug, but still this issue happens sometimes

**Comment by 0x0range** [comment]
Looks like the same issue as #45.
